service: cogeo-mosaic

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'us-east-1'}

  deploymentBucket: ${opt:bucket}

  # Add Tags to resources
  stackTags:
    project: labs
  
  apiGateway:
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1

  # Add other buckets here if needed
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "*"
     Resource:
       - "arn:aws:s3:::${opt:bucket}*"

package:
  artifact: package.zip

functions:
  web:
    handler: cogeo_mosaic.handlers.web.app
    memorySize: 128
    timeout: 3
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal30-py37-cogeo:7
    environment:
      MAPBOX_ACCESS_TOKEN: ${opt:token, ""}
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: get
          cors: true

  tiler:
    handler: cogeo_mosaic.handlers.tiles.app
    memorySize: 1536
    timeout: 10
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal30-py37-cogeo:7
    environment:
      CPL_TMPDIR: /tmp
      GDAL_CACHEMAX: 25%
      GDAL_DATA: /opt/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 50
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /opt/share/proj
      PYTHONWARNINGS: ignore
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    events:
      - http:
          path: /tiles/{proxy+}
          method: any
          cors: true

  mosaics:
    handler: cogeo_mosaic.handlers.mosaic.app
    memorySize: 3008
    timeout: 30
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal30-py37-cogeo:7
    environment:
      CPL_TMPDIR: /tmp
      GDAL_CACHEMAX: 25%
      GDAL_DATA: /opt/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 50
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /opt/share/proj
      PYTHONWARNINGS: ignore
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    events:
      - http:
          path: /mosaic/{proxy+}
          method: any
          cors: true